env_files = [".env.local"]

[build]
cmd = "mise run build-backend"
entrypoint = ["./program"]
include_ext = ["go", "html", "css"]
exclude_dir = ["tmp", "node_modules"]

[[build.rules]]
name = "frontend"
include_file = ["src.js"]
cmd = "mise run build-client"


[proxy]
enabled = false
