steps:
  build:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t antost360/web-ssh:latest .
    when:
      - event: pull_request

  deploy:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --platform=linux/amd64 -t antost360/web-ssh:latest .
      - docker push antost360/web-ssh:latest    
    when:
      - event: push 
        branch: main
