[tools]
bun = "1.4.0"
go = "1.27.0"

[env]
_.file = ".env.local"

[tasks.dev]
description = "run development hot reload server"
run = "air"

[tasks.build-client]
description = "build client assets"
run = "bun build src.js --outdir public/build --target browser"

[tasks.build-backend]
description = "build go server"
run = 'go build -ldflags="-s -w" -o program ./main.go'

[tasks.build]
description = "build whole client and backend in parrarel"
run = [
	{ tasks = ["build-backend", "build-client"]},
]

[tasks.build-docker]
description = "build docker image 'antost360/web-ssh:latest'"
run = "docker build -t antost360/web-ssh:latest ."

[tasks.run-docker]
depends = ["build-docker"]
description = "run docker build locally"
run = 'docker run -p 3000:3000 -v "/Users/antoni-ostrowski/.ssh/known_hosts:/app/config/known_hosts" -v "./dev/config.json:/app/config/config.json" antost360/web-shell-client:latest'
